#include<iostream>
#include<string>
#include<stack>

using namespace std;

/*
Morgan wishes to combined two strings such that the smallest front letter is added first, like a stack for strings

Attempt 1: Followed the prompt and inserted both strings into stack, compared the top of each stack with code to consider the case for
repeating letter segments. This repeating code would make a new stack to which both could add to until a difference occured, which would
allow a comparison to occur. This was very ineffcient.

Attempt 2: Instead of stacks a pair of string iterators was used for each string. The first iterator pointed to the current letter 
position and the second iterator to the character after a repeating sub-string that appeared in both strings. However this method also
failed some test cases so further debugging is required.
*/

void testMorganStringAns(string& my_ans, string& ans)
{
    int ii{0};

    if (my_ans == ans)
    {
        cout << "answers match" << endl;
        return;
    }

    if (my_ans.size() != ans.size())
    {
        cout << "wrong lengths" << endl;
        if(my_ans.size() < ans.size())
            ii=my_ans.size();
        else
            ii=ans.size();
    }
    else
        ii = ans.size();

    for(int i=0; i <ii; i++)
    {
        if (my_ans.at(i) != ans.at(i))
        {
            cout << i << " " << my_ans.at(i) << " " << ans.at(i) << endl;  
            return; 
        }
    }

}

string morganAndString(string a, string b) {

    string::iterator a_iter = a.begin(), b_iter = b.begin(), rep_a_end = a.begin(), rep_b_end = b.begin();
    string::iterator a_last =a.end()-1, b_last =b.end()-1;  
    string min_string;

    int diff{0};

    while(a_iter != a.end() && b_iter != b.end())
    //while(a_iter != a_last && b_iter != b_last)
    {       
        if(*a_iter == *b_iter)
        {
            /*if(a_iter == a_last)
            {
                min_string += *b_iter;
                b_iter++;
            }
            else if(b_iter == b_last)
            {
                min_string += *a_iter;
                a_iter++;
            }*/
            //if (a_iter < rep_a_end && b_iter < rep_b_end)
            //Best attempt
            /*if(rep_a_end == a.end() && rep_b_end == b.end())
            {
                for(string::iterator& i = a_iter; i < rep_a_end; i++)
                    min_string += *i;
                for(string::iterator i = rep_b_end-1; i > b_iter -1; i--)
                    min_string += *i;
                b_iter = b.end();
            }*/
            if (a_iter < rep_a_end && b_iter < rep_b_end)
            {
                if(diff > 0)
                {
                    min_string += *a_iter;
                    a_iter++;
                    /*if(a_iter != a_last)
                    {
                        min_string += *a_iter;
                        a_iter++;
                    }
                    else
                    {
                        min_string += *b_iter;
                        b_iter++;
                    }*/
                }
                else if(diff < 0)
                {
                    min_string += *b_iter;
                    b_iter++;
                    /*if(b_iter != b_last)
                    {
                        min_string += *b_iter;
                        b_iter++;
                    }
                    else
                    {
                        min_string += *a_iter;
                        a_iter++;
                    }*/
                }
            }
            else
            {
                rep_a_end = a_iter;
                rep_b_end = b_iter;
                while(*rep_a_end == *rep_b_end && rep_a_end != a.end() && rep_b_end != b.end())
                {
                    rep_a_end++;
                    rep_b_end++;          
                }

                /*if(*rep_a_end < *rep_b_end || rep_a_end == a.end())
                {
                    diff = 1;
                    min_string += *a_iter;
                    a_iter++;
                }
                else if (*rep_a_end > *rep_b_end || rep_b_end == b.end())
                {
                    diff = -1;
                    min_string += *b_iter;
                    b_iter++;
                }
                else
                    diff = 0;*/

                if(*rep_a_end < *rep_b_end || rep_a_end == a.end())
                {
                    diff = 1;
                    min_string += *a_iter;
                    a_iter++;
                }
                else if (*rep_a_end > *rep_b_end || rep_b_end == b.end())
                {
                    diff = -1;
                    min_string += *b_iter;
                    b_iter++;
                }
                else
                    diff = 0;
            }
        }
        else if(*a_iter < *b_iter)
        {
            min_string += *a_iter;
            a_iter++;
        }
        else if(*a_iter > *b_iter)
        {
            min_string += *b_iter;
            b_iter++;
        }

        /*if(min_string.size() == 8192)
        {
            string str1= "", str2="";
            string::iterator i1,i2, ii1,ii2;
            if (a_iter-5 < a.begin() )
            {
                i1 = a.begin();
                cout << "a begining" << endl;
            }
                
            else
                i1=a_iter-5;
            if (a_iter+5 > a.end() )
            {
                ii1 = a.end();
                cout << "a end" << endl;
            }
            else
                ii1 = a_iter+5;

            if (b_iter-5 < b.begin() )
            {
                i2 = b.begin();
                cout << "b begining" << endl;
            }
            else
                i2=b_iter-5;
            if (b_iter+5 > b.end() )
            {
                ii2 = b.end();
                cout << "b end" << endl;
            }
            else
                ii2 = b_iter+5;

            for(auto i = i1; i < ii1; i++ )
                str1 += *i;
            for(auto i = i2; i < ii2; i++ )
                str2 += *i;
            
            cout << "sizes: " << str1.size() << " , " << str2.size() << endl;
            cout << str1 << endl << str2 << endl;
        }*/
    }

    //cout << min_string.size() << endl;

    /*if(a_iter == a_last)
    {
        while(a_iter != a.end())
        {
            if(*a_iter < *b_iter)
            {
                min_string += *a_iter;
                a_iter++;
            }
            else
            {
                min_string += *b_iter;
                b_iter++;
            }
        }
    }
    else if(b_iter == b_last)
    {
        while(b_iter != b.end())
        {
            if(*b_iter < *a_iter)
            {
                min_string += *b_iter;
                b_iter++;
            }
            else
            {
                min_string += *a_iter;
                a_iter++;
            }
        }
    }*/

    for(string::iterator i = a_iter; i < a.end(); i++)
        min_string += *i;
    for(string::iterator i = b_iter; i < b.end(); i++)
        min_string += *i;

    return min_string;
}

int main()
{
    string first;//{"AAABBAABBBBAA"};//{"JACK"};//{"ACA"};//{"ABACABA"};//{"ABCXYZK"};
    string second; //{"BBAAABBBAB"};//{"DANIEL"};//{"BCF"};//{"ABACABA"};//{"XYZA"};
    string actual_ans;

    first = "DEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDE";
    second = "EEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDE";
    actual_ans = "DEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEDEEDEDDEEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDDEDEEDEDDEDEEDDEEDEDDEEDEDDEE";
    
    //first = "DEEDEDDE";
               
    //second = "EEDEDDE";
    //actual_ans = "DEEDEDDEEDDEDEE";
    string ans = morganAndString(first,second);
    testMorganStringAns(ans,actual_ans);
    //cout << ans<< endl << actual_ans << endl;
    //cout << first.size() << " , " << second.size() << endl;

    return 0;
}
